version: 0.2
phases:
    install:
        runtime-versions:
            python: 3.9
        commands:
            - pip install --upgrade pip
           
            - pip install -r requirements.txt pylint
    pre_build:
        commands:
            - python --version
            - pylint $CODEBUILD_SCR_DIR/*.py
            - pylint $CODEBULD_SCR_DIR/ebporj/*.py
artifacts:
    files:
        - '**/*'